name: FunnyGuilds-Reloaded
main: net.dzikoysk.funnyguilds.FunnyGuilds
version: 3.9.9.1 Cleaned
author: Dzikoysk
website: http://www.dzikoysk.net/
permissions:
    funnyguilds.*:
        default: op
        children:
            funnyguilds.player: true
            funnyguilds.admin: true
    funnyguilds.admin:
        default: op
        children:
            funnyguilds.reload: true
            funnyguilds.admin.build: true
            funnyguilds.admin.notification: true
    funnyguilds.player:
        default: true
        children:
            funnyguilds.create: true
            funnyguilds.delete: true
            funnyguilds.invite: true
            funnyguilds.join: true
            funnyguilds.leave: true
            funnyguilds.kick: true
            funnyguilds.base: true
            funnyguilds.enlarge: true
            funnyguilds.help: true
            funnyguilds.ally: true
            funnyguilds.break: true
            funnyguilds.player: true
            funnyguilds.info: true
            funnyguilds.top: true
            funnyguilds.validity: true
            funnyguilds.leader: true
            funnyguilds.deputy: true
            funnyguilds.ranking: true
            funnyguilds.manage: true
    funnyguilds.reload:
        default: op
    funnyguilds.admin.build:
        default: op
    funnyguilds.admin.notification:
        default: op
    funnyguilds.info:
        default: true
    funnyguilds.create:
        default: true
    funnyguilds.delete:
        default: true
    funnyguilds.invite:
        default: true
    funnyguilds.join:
        default: true
    funnyguilds.leave:
        default: true
    funnyguilds.kick:
        default: true
    funnyguilds.base:
        default: true
    funnyguilds.enlarge:
        default: true
    funnyguilds.help:
        default: true
    funnyguilds.player:
        default: true
    funnyguilds.ally:
        default: true
    funnyguilds.break:
        default: true
    funnyguilds.top:
        default: true
    funnyguilds.validity:
        default: true
    funnyguilds.leader:
        default: true
    funnyguilds.deputy:
        default: true
    funnyguilds.manage:
        default: true
    funnyguilds.ranking:
        default: true

